# Generated by Django 5.1.1 on 2025-05-14 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_1_posts', '0002_alter_comment_post_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
