# Generated by Django 5.1.1 on 2025-05-17 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_1_posts', '0013_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
