# Generated by Django 5.1.1 on 2025-05-18 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_1_posts', '0015_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
