# Generated by Django 5.1.1 on 2025-05-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelfile',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='modelfile',
            name='create_api__path_39bb8f_idx',
        ),
        migrations.RemoveIndex(
            model_name='modelfile',
            name='create_api__is_fold_af586f_idx',
        ),
        migrations.AlterUniqueTogether(
            name='modelfile',
            unique_together={('app', 'name')},
        ),
        migrations.AddIndex(
            model_name='modelfile',
            index=models.Index(fields=['app', 'name'], name='create_api__app_id_b835f6_idx'),
        ),
    ]
