# Generated by Django 5.1.1 on 2024-11-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='full_code',
            field=models.TextField(null=True),
        ),
    ]
