# Generated by Django 5.1.1 on 2025-05-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_api', '0002_alter_modelfile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aichangerequest',
            name='app_name',
            field=models.CharField(blank=True, help_text="The Django app label (e.g. 'project_1_posts') this change targets", max_length=100, null=True),
        ),
    ]
