# Generated by Django 5.1.1 on 2025-05-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_api', '0003_alter_aichangerequest_app_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichangerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='aichangerequest',
            name='app_name',
            field=models.CharField(default='main', max_length=100),
        ),
        migrations.AlterField(
            model_name='aichangerequest',
            name='file_type',
            field=models.CharField(choices=[('template', 'Template'), ('model', 'Model'), ('view', 'View'), ('form', 'Form'), ('app', 'New App'), ('multi', 'Multiple Files'), ('static', 'Static File'), ('other', 'Other')], max_length=32),
        ),
        migrations.AlterField(
            model_name='aichangerequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('applied', 'Applied'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='draft', max_length=16),
        ),
    ]
