# Generated by Django 5.1.1 on 2025-05-15 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_1_users', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
