# Generated by Django 5.1.1 on 2025-05-15 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_1_users', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
