# Generated by Django 5.1.1 on 2025-05-17 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_1_users', '0009_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
