"""
Django settings for api_generator project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# put all dynamic previews in a sibling folder, not under BASE_DIR
PREVIEW_ROOT = BASE_DIR.parent / "dynamic_previews"
# ensure it exists at startup
PREVIEW_ROOT.mkdir(exist_ok=True, parents=True)
# Add DYNAMIC_PREVIEWS_DIR for the preview system
DYNAMIC_PREVIEWS_DIR = BASE_DIR.parent / "dynamic_previews" / "dynamic_apps_preview"
DYNAMIC_PREVIEWS_DIR.mkdir(exist_ok=True, parents=True)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8nnd!w13nd3p9vo^7oa=&i6=4dz55chk2&78_c6*0p1je39mt!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
     "channels",
     'django_extensions',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # 'django.contrib.staticfiles',
    'rest_framework',
        'rest_framework_simplejwt',
    'core.apps.CoreConfig',
    'projects.apps.ProjectsConfig',
# 'django.contrib.staticfiles',

    'corsheaders',  
    'create_api.apps.CreateApiConfig',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]
CORS_ALLOW_CREDENTIALS = True
import sys
from pathlib import Path
DYNAMIC_APPS_PATH = Path(__file__).resolve().parent.parent / "dynamic_apps"
sys.path.insert(0, str(DYNAMIC_APPS_PATH))




REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
     'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # Require authentication for all views
    ],
}
AUTHENTICATION_BACKENDS = [
    "core.backends.ProjectDBBackend",  
    "django.contrib.auth.backends.ModelBackend",
]

MIDDLEWARE = [
    # 1) CORS first so the browser will accept and send cookies
    "corsheaders.middleware.CorsMiddleware",

    # 2) Common (for things like APPEND_SLASH)…
    "django.middleware.common.CommonMiddleware",

    # 3) Session must come before CSRF/Auth
    "django.contrib.sessions.middleware.SessionMiddleware",

    # 4) CSRF checks before you populate request.user
    "django.middleware.csrf.CsrfViewMiddleware",

    # 5) Django's auth middleware to read the session cookie into request.user
    "django.contrib.auth.middleware.AuthenticationMiddleware",

    # 6) Your project-DB routing + login patching
    "core.middleware.ProjectDBMiddleware",
    "core.middleware.PatchRegisterAndLoginMiddleware",
    "core.middleware.PreviewDiffMiddleware",

    # 7) Now swap in the per-project DB user (but don't re-login)
    "core.middleware.ProjectSessionAuthMiddleware",

    # 8) Messaging, etc.
    "django.contrib.messages.middleware.MessageMiddleware",
]


ROOT_URLCONF = 'api_generator.urls'

CSP_SCRIPT_SRC = (
    "'self'",
    "'unsafe-inline'",    # you may already have this
    "'unsafe-eval'",      # ← allow eval() inside those bundles
    "https://code.jquery.com",
    "https://cdn.jsdelivr.net",
)
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': False,
        'OPTIONS': {
             'loaders': [
                'core.loaders.DatabaseLoader',
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ],
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            
        },
    },
]

WSGI_APPLICATION = 'api_generator.wsgi.application'
# Tell Django to use Channels' ASGI app
ASGI_APPLICATION = "api_generator.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
        "CONFIG": {
            "capacity": 1500,
        },
    },
}

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# route project_<id>_app_label to project_<id> database
DATABASE_ROUTERS = ['core.db_router.ProjectRouter']

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}


CORS_ALLOW_ALL_ORIGINS = True

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
STATICFILES_FINDERS = [
    'core.db_static.DatabaseStaticFinder',
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

STATICFILES_STORAGE = 'core.db_static.DatabaseStaticStorage'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
STATIC_URL = '/static/'


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
DEFAULT_FILE_STORAGE = 'core.db_media.HybridMediaStorage'